version: "3.8"
services:
  prod_db:
    image: postgres:14.1-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER = ${POSTGRES_USER}
      - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
      - POSTGRES_DB = ${POSTGRES_DB}
    restart: always
    ports:
      - "5432: 5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - event-booking-api

  core:
    depends_on:
      - prod_db
    build: ./core-service
    networks:
      - event-booking-api
    ports:
      - "5000:5000"

    notification:
      depends_on:
        - core
      build: ./notification-service
      networks:
        - event-booking-api
      ports:
        - "5001:5001"

    rabbitmq:
      image: rabbitmq:management
      container_name: rabbitmq
      ports:

networks:
  event-booking-api:
    driver: bridge
volumes:
  postgres:
