version: "3.8"
services:
  test_db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always
    ports:
      - "5432: 5432"
    networks:
      - event-booking-api

  prod_db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always
    ports:
      - "5432: 5432"
    volumes:
      - /db/postgres/data
    networks:
      - event-booking-api

  api:
    depends_on:
      - prod_db
    build: .
    networks:
      - event-booking-api
    ports:
      - "5000:5000"

networks:
  event-booking-api:
    driver: bridge
volumes:
  postgres-data:
    driver: local
