name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: check out repository and setup node
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm run test
